In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("spam.csv")

In [4]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [6]:
df["spam"]=df["Category"].apply(lambda x : 1 if x == "spam" else 0)

In [7]:
df

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [10]:
df = df.drop(["Category"], axis=1)


In [11]:
df

Message  spam
0     Go until jurong point, crazy.. Available only ...     0
1                         Ok lar... Joking wif u oni...     0
2     Free entry in 2 a wkly comp to win FA Cup fina...     1
3     U dun say so early hor... U c already then say...     0
4     Nah I don't think he goes to usf, he lives aro...     0
...                                                 ...   ...
5567  This is the 2nd time we have tried 2 contact u...     1
5568               Will ü b going to esplanade fr home?     0
5569  Pity, * was in mood for that. So...any other s...     0
5570  The guy did some bitching but I acted like i'd...     0
5571                         Rofl. Its true to its name     0

[5572 rows x 2 columns]

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [13]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7733 sparse matrix of type '<class 'numpy.int64'>'
	with 59135 stored elements in Compressed Sparse Row format>

In [15]:
X_train_cv.shape

(4457, 7733)

In [16]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [17]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [20]:
X_test_cv = v.transform(X_test)

In [21]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       982
           1       0.96      0.91      0.93       133

    accuracy                           0.98      1115
   macro avg       0.97      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [22]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

In [36]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    "hey mohan, a millon dollar in you account"
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 0], dtype=int64)

In [37]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [38]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [39]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       982
           1       0.96      0.91      0.93       133

    accuracy                           0.98      1115
   macro avg       0.97      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [40]:
#exo
#Import necessary libraries

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from  sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report

In [63]:
#1. read the data provided in the same directory with name 'movies_sentiment_data.csv' and store it in df variable

df2 = pd.read_csv("IMDB Dataset.csv")

#2. print the shape of the data
df2.shape


(50000, 2)

In [46]:
#3. print top 5 datapoints
df2.head(5)

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [48]:
df2["sen"]= df2["sentiment"].apply(lambda x : 1 if x == "positive" else 0)

In [51]:
df2.head()

review sentiment  sen
0  One of the other reviewers has mentioned that ...  positive    1
1  A wonderful little production. <br /><br />The...  positive    1
2  I thought this was a wonderful way to spend ti...  positive    1
3  Basically there's a family where a little boy ...  negative    0
4  Petter Mattei's "Love in the Time of Money" is...  positive    1

In [61]:
df2[df2["sentiment"] == "positive"]

review sentiment  sen
0      One of the other reviewers has mentioned that ...  positive    1
1      A wonderful little production. <br /><br />The...  positive    1
2      I thought this was a wonderful way to spend ti...  positive    1
4      Petter Mattei's "Love in the Time of Money" is...  positive    1
5      Probably my all-time favorite movie, a story o...  positive    1
...                                                  ...       ...  ...
49983  I loved it, having been a fan of the original ...  positive    1
49985  Imaginary Heroes is clearly the best film of t...  positive    1
49989  I got this one a few weeks ago and love it! It...  positive    1
49992  John Garfield plays a Marine who is blinded by...  positive    1
49995  I thought this movie did a down right good job...  positive    1

[25000 rows x 3 columns]

In [53]:
X_train, X_test, y_train, y_test = train_test_split(df2.review, df2.sen, test_size=0.2)

In [58]:
X_train.head()

40503    Seven pioneer kids strive independently across...
44317    I cant describe how terrible this movie is. Am...
12861    i have lost count as to how many times i have ...
42708    This film was really terrible.<br /><br />Howe...
32938    This movie is about a young girl who goes to l...
Name: review, dtype: object

In [56]:
y_train.head()

40503    0
44317    0
12861    1
42708    0
32938    0
Name: sen, dtype: int64

In [64]:
v2 = CountVectorizer()

In [65]:

X_train_cv = v2.fit_transform(X_train.values)
X_train_cv

<40000x92961 sparse matrix of type '<class 'numpy.int64'>'
	with 5468382 stored elements in Compressed Sparse Row format>

In [66]:
model2 = MultinomialNB()
model2.fit(X_train_cv, y_train)

MultinomialNB()

In [69]:
X_test_cv = v2.transform(X_test)

In [70]:
y_pred = model2.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.84      0.87      0.85      5063
           1       0.86      0.83      0.84      4937

    accuracy                           0.85     10000
   macro avg       0.85      0.85      0.85     10000
weighted avg       0.85      0.85      0.85     10000



In [71]:
model3 = RandomForestClassifier()

In [73]:
clf = Pipeline([
    ('vectorizer', CountVectorizer()),                                                    #initializing the vectorizer
    ('random_forest', (RandomForestClassifier(n_estimators=50, criterion='entropy')))      #using the RandomForest classifier
])



#2. fit with X_train and y_train
clf.fit(X_train, y_train)


#3. get the predictions for X_test and store it in y_pred
y_pred = clf.predict(X_test)


#4. print the classfication report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.84      0.84      0.84      5063
           1       0.83      0.84      0.84      4937

    accuracy                           0.84     10000
   macro avg       0.84      0.84      0.84     10000
weighted avg       0.84      0.84      0.84     10000



In [75]:
!nvidia-smi

Tue Sep 24 10:55:43 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 561.09                 Driver Version: 561.09         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3070 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   51C    P0             29W /  100W |       0MiB /   8192MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----